package-lock.json, src/App.js, src/SDK/DataSdk.js, src/components/Navbar.js, src/pages/Data.js
- parameterize accession in URL
- links to SRA, Trace, BAM
- update search field
- preliminary parsing of summary file info
Full list of tasks: https://github.com/serratus-bio/serratus.io/wiki/Report-Page-Tasks
=> Update report page

.vscode/launch.json, package-lock.json, package.json, src/App.js, src/SDK/D3Heatmap.js, src/SDK/DataSdk.js, src/components/Heatmap.js, src/components/Navbar.js, src/components/Visual.js, src/pages/About.js, src/pages/Data.js, src/pages/Home.js, src/pages/Projects.js
Live demo: https://dev-dan-data-table.serratus.io/Data
There are no merge conflicts. This change completed the following:
- Add Heatmap.js to /Components from /Pages
- Get accession for Heatmap from the searchbox in the UI (still need to add error checks)
- Position Heatmap.js component on the Data page
=> Dev dan data table

src/pages/Data.jsx, src/styles/main.css
Live preview: https://dev-style.serratus.io/data?accession=ERR2756788
ref #15
=> Fix sizing of HTML elements for small width and height

src/pages/Report.jsx
Live preview: https://dev-report-ui.serratus.io/report?accession=ERR2756788
=> Report: add buttons to external links, improve search UI

src/pages/Report.jsx
Live preview: https://dev.serratus.io/
Changes since last release:
- Fix: report page loading issue (#22)
- Enhancement: add buttons to external links, improve search UI (#21)
=> Report page fixes and updates

src/SDK/DataSdk.jsx, src/SDK/drawRunResults.js, src/components/QueryResult.jsx
- remove endpoints for api.serratus.io
- update JSON keys for differences in returned results
fixes #32
=> Update summary API endpoint

src/components/QueryResult.jsx, src/pages/Query.jsx
- update visual states for errors/empty result set
- add top/bottom padding to query result/message
Live preview: https://dev-query-fix.serratus.io/query?run=SRR10980630
fixes #35
=> Add error checking to query results

src/App.jsx, src/pages/Access.jsx
As requested per #38.
Live preview: https://dev-access-redirect.serratus.io/access
=> Redirect /access -> wiki page

.env, .env.development, package-lock.json, package.json, src/index.jsx
Live preview: https://dev-g-analytics.serratus.io/
=> Add NODE_ENV, Google Analytics tracking

src/pages/Query.jsx
Added a dropdown search for `family` on the Query page.
Live preview: https://dev-query-dropdown.serratus.io/query
ref #51
=> Query: family dropdown search

src/App.jsx, src/index.jsx
- track first load
- track URL parameters (using `window.location.search`)
- domain tracking set up separately in Google Analytics view filter
Live preview: https://dev-update-tracking.serratus.io/
=> Improve URL tracking

src/components/Navbar.jsx
Live preview: https://dev-navbar.serratus.io
- add preprint link
- decrease margin for external links
=> Navbar: add preprint link

src/components/DataReference.jsx, src/components/Navbar.jsx, src/pages/Explore.jsx, src/pages/Query.jsx
- Navbar: add preprint link (#71)
- Explore, Query: add references to Access Data Release, preprint citation (#72)
=> Update prod for v0.6.4

src/components/DataReference.jsx, src/pages/Explore.jsx, src/pages/Query.jsx
Live preview: https://dev-data-reference.serratus.io/explore
- make text smaller, slight gray
=> Update styling on data reference text

.github/workflows/node.js.yml, src/components/FilterSlider.jsx, src/pages/Query.jsx
- Fix build warnings
- Add GitHub action workflow to check for build issues upon PR (no testing yet - #60)
=> Add GitHub workflow with build step

src/components/Explorer/Intro.jsx, src/components/Explorer/QueryBuilder.jsx, src/pages/Home.jsx
Add a button to Serratus Explorer Intro page to link to the wiki tutorial.
Live preview: https://dev-wiki-button.serratus.io/
=> Add Serratus Explorer wiki button

src/components/Navbar.jsx
Update navigation bar to include Serratus Wiki link
This pull request addresses issue #...
- Add a short title and describe your changes here
=> Add wiki link to navbar

src/components/Explorer/ApiCalls.jsx, src/components/Explorer/Result/EntrezApiCalls.jsx, src/components/Explorer/Result/ResultHelpers.jsx, src/components/Explorer/Result/SerratusApiCalls.jsx
- update API calls for serratus-bio/serratus-summary-api#7
- separate files for Entrez, Serratus API calls
=> Update API calls for new routes

src/components/Explorer/Result/Chart/GenericChart.jsx, src/components/Explorer/Result/Chart/RunChart.jsx
=> Use run_id column name from API

src/common/LinkButton.jsx, src/components/Explorer/Base/Result/MatchingRuns/SerratusApiCalls.jsx, src/components/Explorer/Nucleotide/LinkButtons.jsx, src/components/Explorer/Rdrp/LinkButtons.jsx
Line 5-17 in `/src/components/Explorer/Base/Result/MatchingRuns/SerratusApiCalls.jsx`
```
export const getAnalysisIndexUrl = (run_id) => {
const params = {
run_id: run_id,
}
params[run_id] = run_id
return `${baseUrl}/index/run=${run_id}`
}
export const getAnalysisMicro = async (run_id) => {
const AnalysisUrl = getAnalysisIndexUrl(run_id)
const response = await axios.get({ AnalysisUrl })
return response
}
```
To the LinkButton added this in src/common/LinkButton.jsx I added option to hide
```
if (show) {
return (
<button className='bg-gray-200 hover:bg-gray-400 mx-2 py-1 px-4 rounded inline-flex items-center'>
<a className='text-blue-500' {...aAttrs} href={link} download={download}>
{text}
{icon}
</a>
</button>
)
} else {
return null
}
```
I can't get a proper API return
```
const …
```
=> Serratus Analysis Index API calls and Link Buttons

src/App.jsx, src/common/routes.jsx, src/components/Explorer/Nucleotide/LinkButtons.tsx, src/components/Explorer/Rdrp/LinkButtons.tsx, src/components/Geo/SelectionInfo.tsx, src/components/Navbar.tsx, src/pages/Home.jsx
This introduces no noticeable differences compared to the current build.
=> Move route paths to separate config file

src/data/teamData.json
This pull request addresses issue #...
- Add Binoy to dev team
- Update AB affiliation to current
=> Welcome aboard Binoy!

src/components/Navbar.tsx
This pull request addresses issue #...
- Add a short title and describe your changes here
=> Update preprint to paper link

.github/workflows/dependabot-auto-merge.yml
Fixes https://github.com/serratus-bio/serratus.io/pull/175#issuecomment-1054575791 per https://github.com/dependabot/dependabot-core/issues/4893#issuecomment-1077612299
=> Use dependabot/fetch-metadata@main

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Make it easier for others to contribute.
_N/A_
=> Update contributing guide and PR template

src/components/Palmid/Palmid.tsx
The link in the navbar was updated in #167 but this one was skipped. Also, make reference links open in a new tab.
=> Update palmid reference links

src/components/Explorer/Nucleotide/Intro.tsx, src/components/Explorer/Nucleotide/LinkButtons.tsx, src/components/Explorer/Rdrp/Intro.tsx, src/components/Explorer/Rdrp/LinkButtons.tsx, src/components/Jbrowse.jsx
- QA using [AWS amplify page](https://update-to-lovelywater2.serratus.io)
https://github.com/serratus-bio/serratus.io/issues/240
=> Update lovelywater namespace to lovelywater2

src/components/Explorer/Base/Result/RunLookup/PalmPrintsTable.tsx, src/components/Geo/Geo.tsx
- Add BLAST link as requested here: https://github.com/serratus-bio/serratus.io/pull/244#issuecomment-1496266302
- Not familiar with the NIH tool, so some QA help would be appreciated
https://github.com/serratus-bio/serratus.io/pull/244#issuecomment-1496266302
=> Add BLAST linkout in results table

src/components/ToolIntro.tsx
Update link to new palmdb repo
https://github.com/ababaian/palmdb/issues/2
=> Update link to new palmdb repo
