src/SDK/D3Heatmap.js, src/pages/Data.js
Live preview: https://dev-text-columns.serratus.io/data?accession=ERR2756788
- add side table with columns: `Score`, `Identity%`, `Reads`, `Coverage%`
- increase font size of family/accession labels
- increase overall width, make SVG responsive (`viewBox`)
- remove families text section
=> Add text columns to heatmap

src/pages/Report.jsx
Issue: search invocation fails to reload to desired report page. Observed on Firefox, Chrome browsers.
Cause: premature setting of `sraAccession` caused this condition to be true in the wrong scenario:
```js
// clicked "Report" on navigation bar
if (sraAccession && !currentAccession) {
loadAccessionPage(currentAccession);
}
```
=> Fix report page search loading issue

src/pages/Home.jsx
Was stuck in D3 mode so I used `<text>` which triggers a console warning in development mode:
> Warning: The tag <text> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
Changed to the more appropriate `<span>`.
=> Home: replace <text> with <span>

src/SDK/DataSdk.jsx
Looks like #43 accidentally used `esearch` for both Entrez GET routes. Reverting to use `esummary` where needed. My bad for not catching that when reviewing 😬 
Live preview: https://dev-fix-query-title.serratus.io
ref #27
=> Query: fix title fetching

src/SDK/DataSdk.jsx, src/SDK/drawQueryResults.js, src/components/ExploreChart.jsx, src/components/QueryIntro.jsx, src/helpers/QueryPageHelpers.jsx, src/pages/Explore.jsx
Associations between SRA runs and GenBank accessions/families are described as "matches" in the paper. Updating all references in codebase to reflect that.
Visual changes:
1. Explore page: Y axis label, text above dropdown
- old: https://dev.serratus.io/explore
- new: https://dev-fix-terminology.serratus.io/explore
2. Query intro text
- old: https://dev.serratus.io/query
- new: https://dev-fix-terminology.serratus.io/query
3. Query Column text
- old1: https://dev.serratus.io/query?family=Coronaviridae
- new1: https://dev-fix-terminology.serratus.io/query?family=Coronaviridae
- old2: https://dev.serratus.io/query?genbank=EU769558.1
- new2: https://dev-fix-terminology.serratus.io/query?genbank=EU769558.1
=> Update terminology for SRA associations

package-lock.json, package.json, src/components/ExploreChart.jsx, src/components/FilterSlider.jsx, src/helpers/common.jsx, src/pages/Explore.jsx, src/pages/Query.jsx
This pull request will close #62 and close #63.
Live preview: https://dev-explore-histogram.serratus.io/explore
- Convert Explore chart to histogram
- Note: performance is noticeably slower than the current area chart. D3 has to render several rectangles per color rather than one continuous shape.
- Use viridis color scale for score/coverage value domain
TODO
- ~optimize rendering where possible~
=> Explore chart: match look of figure in paper

src/pages/Jbrowse.jsx
- change chunkSizeLimit to 40000000
- Response to this bug found: 
- Live Preview: https://fix-lohrd-jbrowse-data-limit.d1w6d75be7tofa.amplifyapp.com/query?run=SRR6197347&identity=%5B75-100%5D&coverage=%5B0-100%5D
- Click on Parvoviridae and expand the top Accession 'NC_012042.1' to click and view corrected alignment
=> Add bigger limit to Jbrowse BAM loads

src/components/Explorer/Result/ResultHelpers.jsx, src/components/Explorer/Result/SerratusApiCalls.jsx, src/components/Explorer/Result/index.jsx
This pull request addresses issue #99.
Live preview: https://dev-download-matches.serratus.io/explorer?genbank=NC_034446.1
- consolidate family/genbank API calls
- add button to download all matches, positioned below search results
=> Add button to download all matches

src/components/Navbar.jsx
Live preview: https://dev-navbar.serratus.io
- Add **Map (beta)** -> /geo
- Remove **GitHub** -> github.com/ababaiain/serratus
- not a fan of too many external links in navbar, plus **Wiki** already points to the repo.
=> Update navbar links: add Map, remove external GitHub

src/components/Geo/MapPlot.jsx, src/components/Geo/README.md, src/components/Geo/SelectionInfo.jsx
Live preview: https://dev-geo.serratus.io/geo
- fix query to remove duplicate `run_id` rows, add source query in README
- update detail table with sample source taxonomy name linking to NCBI Taxonomy Browser
=> Update geo data with organism id/name, fix query

src/components/Geo/MapPlot.jsx, src/components/Geo/index.jsx
Current behaviour is that clicking has no effect on the map and double-click resets the map to a full world view.
see: www.serratus.io/geo
-----------------
In `plotly` there is a `layout` setting for all graphs and one of the settings is (`clickmode`](https://plotly.com/python/reference/layout/#layout-clickmode). This defaults to `event` setting but I guess we have no event triggers to make use of this.
I've chnaged `clickmode` to `select` which allows me to set a given point as selected (the same as when box-select is used on multiple points). To confirm this I've changed the color of selected points to "purple" (feature we should include).
The problem currently is that click-select is not loading the table-results of `SelectionInfo` (table below the graph). I can't figure out how the …
=> Click to select Feature of Map -- Development

src/components/Explorer/Base/QueryBuilder/CountChart.jsx, src/components/Explorer/Base/Result/MatchingRuns/Result.jsx, src/components/Explorer/Nucleotide/Intro.jsx, src/components/Explorer/Rdrp/Intro.jsx, src/components/Explorer/Rdrp/index.jsx
Updated the wording and examples for hte RdRP/NT Intro pages.
[Dev Page Link](https://rdrp-doc.d1w6d75be7tofa.amplifyapp.com/)
- Added triangle unicode to section titles to indicate it is click to expand
-  Moved the "search image overview" to within the Search Information tab.
- Moved "Download Matches" button to top of results page
- Added data-share message to click-on-mascots
- Some minor typo and documentation fixes
- Query Chart now uses increments of 5 instead of 2 to prevent overplotting of numbers
=> RdRP/NT Intro Documentation

src/App.jsx, src/components/Navbar.jsx
We need to retain links like https://serratus.io/explorer?run=ERR2756788.
Live preview: https://dev-routes.serratus.io/explorer?run=ERR2756788
=> Restore /explorer route as primary, remove stale redirects

package-lock.json, package.json, src/App.jsx
The single transition used by `react-spring` in our app doesn't seem to make any visual difference with or without it.
Live preview: https://dev-refactor.serratus.io
=> Remove react-spring transition

package.json, src/common/routes.jsx, src/components/Explorer/Base/QueryBuilder/QueryBuilder.jsx
Live preview: https://dev-routes.serratus.io/
After fixing #127, we can now use new routes per https://github.com/serratus-bio/serratus.io/discussions/120#discussioncomment-478736:
- `/explorer` -> `/explorer/nt`
- `/explorer-rdrp` -> `/explorer/rdrp`
Modified `Redirect`s to include URL query parameters so old links like these are re-routed properly:
- https://serratus.io/explorer?run=ERR2756788&identity=45-100&score=50-100
- https://serratus.io/explorer-rdrp?sequence=NC_001653&identity=45-100&score=50-100
Also, removed stale redirects:
- `/query`
- `/family`
- `/explore`
- `/explorer-nt`
ref #112
=> Use nested routes for Explorer

src/components/Explorer/Base/Result/MatchChart/IMatchRow.tsx
Fixes a bug introduced by #143 where JBrowse links go to `/explorer/jbrowse?...`.
Live preview: https://dev-routes.serratus.io/
=> Fix JBrowse link with nested URL path

src/components/Explorer/Base/QueryBuilder/QueryBuilder.jsx, src/components/Explorer/Base/QueryBuilder/debounce.js
Current: https://serratus.io/explorer/rdrp
Preview: https://dev-chart.serratus.io/explorer/rdrp
Currently, the chart contents (one `rect` per identity+score bin) are redrawn by D3 every time the value of a range slider changes. This makes it extremely sluggish on the average machine.
This is a common problem with web events (`onChange`, `onScroll`, etc.) and a good solution is the [debounce function](https://davidwalsh.name/javascript-debounce-function). Downside is a slight delay before actual invocation, but that's much more favorable than the existing lag.
=> Use debounce function to Improve performance of match count chart

src/components/Trees/Trees.tsx
- Add species labels where available.
- Remove known vs. novel tip coloring. From @rcedgar:
> decided to drop it because coloring will quickly be obsolete, too much bother to keep this updated
> the "right" way to do it long term would be to integrate the web site with palmdb
- Direct users to use the MSA viewer or SVG download to read tip labels.
=> Trees: update tip info, new SVGs and user guidance

src/components/Explorer/Base/BaseContext.tsx, src/components/Explorer/Base/ExplorerBase.tsx, src/components/Explorer/Nucleotide/NucleotideExplorer.tsx, src/components/Explorer/Rdrp/RdrpExplorer.tsx
Set the default score filter range for the `run` search level to `[0,100]` for both Nucleotide and RdRP Explorer. This only affects URLs that are direct links without any range set in the URL params (e.g. https://dev.serratus.io/explorer/rdrp?run=ERR2756788 will show `[0,100]` which is new behavior, but an explicit link https://dev.serratus.io/explorer/rdrp?run=ERR2756788&identity=45-100&score=50-100 will still show `[50,100]`.
Switching between filter levels in the query builder also has no affect on the filter ranges (the default ranges are only applied on page load).
Closes #161.
=> Set default score filter range for run level to 0-100

src/common/routes.jsx
This pull request addresses @ababaian's Slack thread: [Create a simple "Join the mailing list" page](https://hackseq-rna.slack.com/archives/C012FU1JF0V/p1646653474043629)
Try: https://community-redirect.serratus.io/community
Another option would be to embed the form in an `<iframe>`, but that can come later and this simple redirect is better than nothing.
=> Add `/community` redirect to Google form

src/common/routes.jsx
Change to serratus.io/access to be a direct link, does not use access component
=> fix Access link

.github/workflows/dependabot-auto-merge.yml
Fixes error in [this run](https://github.com/serratus-bio/serratus.io/runs/6182669416?check_suite_focus=true):
```
Run gh pr merge --auto --merge "$PR_URL"
Message: ["Merge method merge commits are not allowed on this repository"], Locations: [{Line:1 Column:72}]
Error: Process completed with exit code 1.
```
=> Use squash merge for dependabot auto-merge

src/components/Trees/Trees.tsx
Hello, I have developed [a tool](https://taxonium.org/) for exploring large trees, largely [for SARS-CoV-2](https://cov2tree.org/). I was considering other projects that might benefit from such a tool, and Serratus seemed a possible candidate.
This PR would add a button that enables exploring any of the trees interactively using Taxonium.
E.g. [Levivirales](https://taxonium.org/?treeUrl=https%3A%2F%2Fs3.amazonaws.com%2Fserratus.io%2Ftrees-2021-11-27%2Fnewick%2FLevivirales.newick&ladderizeTree=false&config=%7B%22title%22%3A%22Serratus%3A%20Levivirales%22%7D) (62k nodes)
[Coronaviridae](https://taxonium.org/?treeUrl=https%3A%2F%2Fs3.amazonaws.com%2Fserratus.io%2Ftrees-2021-11-27%2Fnewick%2FCoronaviridae.newick&ladderizeTree=false&config=%7B%22title%22%3A%22Serratus%3A%20Coronaviridae%22%7D) …
=> Adds a tree explorer link-out

src/components/Trees/Trees.tsx
This adds TSV metadata from @ababaian. See also discussion on Slack.
It works well, I hadn't thought about the fact that you are now able to search based on sequence fragments using the Taxonium interface.
Btw it looks like not all nodes are found in the metadata 
```
wget https://s3.amazonaws.com/serratus.io/trees-2021-11-27/metadata/Wolframvirales.tsv
grep u201806 Wolframvirales.tsv 
```
does not return anything (I'm not 100% sure if that's unexpected)
=> Add Taxonium metadata

src/components/Palmid/Palmid.tsx, src/components/Palmid/hooks/useFasta.tsx
The number of requests before a timeout is bumped from 60 to 120. 
Here's an example of a sequence that used to fail on a 60-request timeout limit: 
```
>betaflax_sativa
SNQFNDMKTLRGKNWNNYVYVFETIYPRHQSSDDLTFFAAIQKRLLRSNP
EKEARKLEKSWGIGSIMFHELKRTLGLNPNVYIDEEVVNREFVQKRLNKS
AKLIENHSGRSDPDWRLDHFFLFMKSQLCTKFEKRFVDAKAGQTLACFSH
QILTRFGVAFRTFEKKFSANLPKTWYVHTMKNFDQLNLWACENVKEREGT
ESDYEAFDRSQDAPILAFEILMLRFFNWPEDLIQDYKMIKLWMGCRLGAV
AIMRFTGEFGTFFFNTLVNMAFTVMRYHVNKESVIAFAGDDMYAAGFLKR
RVDLEFALDQLTLKAKVQFTRRPMFCGWYMTPMGIVKEPRLVLERWKIAE
QKGNLRDVIINYALEVSYGYRLGEYLWEVLDNLESQQEIVRNIVKSKHLL
PLKVRHFFSAVDNETLSTEF
```
After increasing the request limit, an error report was returned as expected here: https://s3.amazonaws.com/openvirome.com/betaflax_sativa.html
In addition to the change made here, the timeout for …
=> Bumped the number of PalmID requests

src/components/Palmid/Palmid.tsx
Add short text label to use only `amino acid` input for palmId currently until bug is fixed.
=> Add palmID aa-bug warning

src/components/Explorer/Rdrp/LinkButtons.tsx
Add an `Assembly` download button to the Explorer page if there is an `assembly` file available.
=> Add link-out to de novo assembly files on Explorer page

src/components/Explorer/Base/Result/SerratusApiCalls.tsx, src/components/Geo/Geo.tsx, src/components/Geo/MapPlot.tsx
- Integrate MapPlot with paginated geo endpoint (https://github.com/serratus-bio/serratus-summary-api/pull/37)
- Note, given the large number of geo points (93034 rows) it will be important that the server caches results.
https://github.com/serratus-bio/serratus.io/issues/225
Manual testing:
- Check all data-points are fetched and rendered on map
- Select single and multiple points with shift+click and lasso
=> Integrate MapPlot with RdRP geo API

src/components/Explorer/Base/Result/SerratusApiCalls.tsx
- This is needed to support fetching all run_ids instead of using pagination route
- Renaming the download route in order to replace the existing matches route to return JSON
- New route has been deployed: https://github.com/serratus-bio/serratus-summary-api/pull/46
- can test URL: https://api.serratus.io/matches/rdrp/download?scoreMin=50&scoreMax=100&identityMin=45&identityMax=100&family=Alphaflexiviridae
=> Update matches download URL

package-lock.json, package.json, src/common/LoadIcon.tsx, src/components/Explorer/Base/Result/MatchChart/MatchChartController.tsx, src/components/Explorer/Base/Result/Result.tsx, src/components/Explorer/Base/Result/RunLookup/PalmPrintsTable.tsx, src/components/Explorer/Base/Result/SerratusApiCalls.tsx, src/components/Explorer/Base/Result/withTabs.tsx, src/components/Geo/Geo.tsx, src/components/Geo/GeoHelpers.tsx, src/components/Geo/MapPlot.tsx, src/components/Trees/Trees.tsx
- Add new lib react-tabs
- Add higher-order component for rendering tabs on Sequence and Family pages in explorer and fetching all RunIDs
- Handle conditional behaviour for large number of run_ids in query params
- Add info about available geo data vs total runs   
- Misc request: change text from `Analyse` -> `Palmprint` 
- https://github.com/serratus-bio/serratus.io/issues/111
- https://github.com/serratus-bio/serratus.io/issues/226
- https://github.com/serratus-bio/serratus.io/issues/115
=> Add Geo tab to explorer pages
